package com.uberotel.b2b.business.domain;
// Generated Oct 26, 2016 11:37:23 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * DigitalAsset generated by hbm2java
 */


		
public class DigitalAsset implements java.io.Serializable {

	private Long digitalAssetId;
	private String assetType;
	private String hotelName;
	private String roomTypeDesc;
	public String getHotelName() {
		return hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	public String getRoomTypeDesc() {
		return roomTypeDesc;
	}

	public void setRoomTypeDesc(String roomTypeDesc) {
		this.roomTypeDesc = roomTypeDesc;
	}

	private Long hotelId;
	private Integer roomTypeId;
	private Long roomId;
	private String useRoomType;
	private Integer noOfAssets;
	private String assetDetail;
	private Integer assetResHtPx;
	private Integer assetResWdPx;
	private Date created;
	private String createdBy;
	private Date updated;
	private String updatedBy;

	public DigitalAsset() {
	}

	public DigitalAsset(String assetType) {
		this.assetType = assetType;
	}

	public DigitalAsset(String assetType, Long hotelId, Integer roomTypeId, Long roomId, String useRoomType,
			Integer noOfAssets, String assetDetail, Integer assetResHtPx, Integer assetResWdPx, Date created,
			String createdBy, Date updated, String updatedBy) {
		this.assetType = assetType;
		this.hotelId = hotelId;
		this.roomTypeId = roomTypeId;
		this.roomId = roomId;
		this.useRoomType = useRoomType;
		this.noOfAssets = noOfAssets;
		this.assetDetail = assetDetail;
		this.assetResHtPx = assetResHtPx;
		this.assetResWdPx = assetResWdPx;
		this.created = created;
		this.createdBy = createdBy;
		this.updated = updated;
		this.updatedBy = updatedBy;
	}

	
	

	
	public Long getDigitalAssetId() {
		return this.digitalAssetId;
	}

	public void setDigitalAssetId(Long digitalAssetId) {
		this.digitalAssetId = digitalAssetId;
	}

	
	public String getAssetType() {
		return this.assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	
	public Long getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(Long hotelId) {
		this.hotelId = hotelId;
	}

	
	public Integer getRoomTypeId() {
		return this.roomTypeId;
	}

	public void setRoomTypeId(Integer roomTypeId) {
		this.roomTypeId = roomTypeId;
	}

	
	public Long getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Long roomId) {
		this.roomId = roomId;
	}

	
	public String getUseRoomType() {
		return this.useRoomType;
	}

	public void setUseRoomType(String useRoomType) {
		this.useRoomType = useRoomType;
	}

	
	public Integer getNoOfAssets() {
		return this.noOfAssets;
	}

	public void setNoOfAssets(Integer noOfAssets) {
		this.noOfAssets = noOfAssets;
	}

	
	public String getAssetDetail() {
		return this.assetDetail;
	}

	public void setAssetDetail(String assetDetail) {
		this.assetDetail = assetDetail;
	}

	
	public Integer getAssetResHtPx() {
		return this.assetResHtPx;
	}

	public void setAssetResHtPx(Integer assetResHtPx) {
		this.assetResHtPx = assetResHtPx;
	}

	
	public Integer getAssetResWdPx() {
		return this.assetResWdPx;
	}

	public void setAssetResWdPx(Integer assetResWdPx) {
		this.assetResWdPx = assetResWdPx;
	}

	
	
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	
	
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
